// vue.js/src/components/management/talks/TalkTableList.vue
<template>
  <div>
    <cp-page-header :headers="['Talks', 'List']">
      <span class="title is-4 is-info is-pulled-right">
        <router-link class="icon is-large" to="/secure/talk">
          <i class="fa fa-plus-circle"></i>
        </router-link>
      </span>
    </cp-page-header>
    <div class="section">
      <div class="container">
        <div class="columns">
          <div class="column">
            <cp-table
              :labels="['ID', 'Name', 'City', 'Country', 'Start Date']"
              :amountPerPage="amountPerPage"
              :total="total"
              :pageNumber="pageNumber"
              :navigateToPage="navigateToPage"
            >
              <cp-talk-table-row
                v-for="talk in talks"
                :talk="talk"
                :deleteTalk="deleteTalk"
                :key="talk.id"
              ></cp-talk-table-row>
            </cp-table>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>


<script>
import {DEFAULT_ITEMS_PER_PAGE, START_PAGE} from '../../../constant';
import PageHeader from '../../shared/PageHeader.vue';
import Table from '../../shared/Table.vue';
import {deleteTalk, getAllTalks} from '../management.apollo-query';
import TalkTableRowItem from './TalkTableRowItem.vue';

export default {
  name: 'talks',
  data() {
    return {
      amountPerPage: DEFAULT_ITEMS_PER_PAGE,
      total: 0,
      pageNumber: START_PAGE
    };
  },
  computed: {
    skip() {
      return (this.pageNumber - 1) * this.amountPerPage;
    }
  },
  apollo: {
    // TODO: Write getAllTalks
  },
  methods: {
    navigateToPage(pageNumber) {
      this.pageNumber = pageNumber;
    },
    deleteTalk(id) {
      // TODO: Write deleteTalk
      // Replace Promise.reject() by the correct call
      Promise.reject()
        .then(({data}) => this.refetchAllTalks(DEFAULT_ITEMS_PER_PAGE))
        .then(({data}) => {
          this.pageNumber = 1;
          this.total = data._allTalksMeta.count;
        });
    },
    refetchAllTalks(first, skip = 0) {
      // TODO: implement a fetchMore for the queries talks
      // Replace Promise.reject() by the correct call
      return Promise.reject();
    }
  },
  components: {
    'cp-page-header': PageHeader,
    'cp-table': Table,
    'cp-talk-table-row': TalkTableRowItem
  }
};
</script>

// angular/src/app/management/talk-table-list.component.ts
import { Component, OnDestroy, OnInit } from "@angular/core";
import { Apollo } from "apollo-angular";
import { DEFAULT_ITEMS_PER_PAGE, START_PAGE } from "../table.config";
import { Talk } from "../talk/types";
import { Subscription, empty } from "rxjs";
import { unsubscribeAll } from "../utils";
import {
  deleteTalk,
  getAllTalks,
  getAllTalksResponse
} from "./management.apollo-query";
import { switchMap } from "rxjs/operators";

@Component({
  selector: "cp-talk-table-list",
  template: `
    <div>
      <cp-page-header
        [headers]="['Talks']">
        <span class="title is-4 is-info is-pulled-right ">
          <a class="icon is-large"
             routerLink="/secure/talk">
            <i class="fa fa-plus-circle"></i>
          </a>
        </span>
      </cp-page-header>
      <div class="section">
        <div class="container">
          <div class="columns">
            <div class="column">
              <cp-table
                [labels]="['ID', 'title', 'Room', 'Starts At']"
                [amountPerPage]="amountPerPage"
                [total]="total"
                [pageNumber]="pageNumber"
                [navigateToPage]="navigateToPage">
                <tr cp-talk-table-row *ngFor="let talk of talks"
                    [talk]="talk"
                    [deleteTalk]="deleteTalk">
                </tr>
              </cp-table>
            </div>
          </div>
        </div>
      </div>
    </div>
  `
})
export class TalkTableListComponent implements OnInit, OnDestroy {
  talks: Talk[];
  amountPerPage = DEFAULT_ITEMS_PER_PAGE;
  total = 0;
  pageNumber = START_PAGE;
  private subscriptions: Subscription[] = [];

  constructor(private apollo: Apollo) {
    this.deleteTalk = this.deleteTalk.bind(this);
    this.navigateToPage = this.navigateToPage.bind(this);
  }

  ngOnInit() {
    this.getTalksChunk();
  }

  navigateToPage(pageNumber) {
    this.getTalksChunk(pageNumber);
  }

  getTalks(pageNumber = 1) {
    // TODO: Write getAllTalks
    return empty();
  }

  deleteTalk(id) {
    // TODO: Write deleteTalk
    const deleteTalk$ = empty()
      .pipe(switchMap(_ => this.getTalks()))
      .subscribe(({ data }) => {
        this.talks = data.talks;
        this.total = data._allTalksMeta.count;
        this.pageNumber = 1;
      });
    this.subscriptions = this.subscriptions.concat(deleteTalk$);
  }

  getTalksChunk(pageNumber = 1) {
    const getAllTalks$ = this.getTalks(pageNumber).subscribe(({ data }) => {
      this.talks = data.talks;
      this.total = data._allTalksMeta.count;
      this.pageNumber = pageNumber;
    });

    this.subscriptions = this.subscriptions.concat(getAllTalks$);
  }

  ngOnDestroy(): void {
    unsubscribeAll(this.subscriptions);
  }
}
