// vue.js/src/components/speaker/SpeakerDetails.vue
<template>
  <div>
    <div class="section">
      <div class="container">
        <div class="columns">
          <div class="column">
            <p class="title is-3 has-text-muted">{{speaker.bio}}</p>
            <hr>
            <p class="title is-4">Talks :</p>
            <div class="columns" v-for="talks in chunkTalks">
              <div class="column is-6" v-for="talk in talks">
                <cp-talk-card :talk="talk"></cp-talk-card>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {split} from '../../utils';
import TalkCard from '../talk/TalkCard.vue';
import {getSpeakerById} from './speaker.apollo-query';

export default {
  name: 'SpeakerDetails',
  data() {
    return {
      speaker: {}
    };
  },
  computed: {
    chunkTalks() {
      return split(3, this.speaker.talks);
    }
  },
  apollo: {
    // TODO: Write getSpeakerById
  },
  components: {
    'cp-talk-card': TalkCard
  }
};
</script>

// react-app/src/component/speaker/SpeakerDetails.js
import gql from "graphql-tag";
import React from "react";
import { QueryWithDefaultLoadingAndError } from "../../apollo";
import { divideInRows } from "../../utils";
import TalkOverview from "../talk/TalkOverview";

// TODO write a query to getSpeakerById
const SPEAKER = undefined;

const SpeakerDetails = ({
  match: {
    params: { id }
  }
}) => (
  <>
    <>
      <div className="section product-header">
        <div className="container">
          <div className="columns">
            <div className="column">
              <span className="title is-3">{username}</span>
              <span className="title is-3 has-text-muted">
                {` @${publicName}`}
              </span>
            </div>
          </div>
        </div>
      </div>
      <div className="section">
        <div className="container">
          <div className="columns">
            <div className="column">
              <p className="title is-3 has-text-muted">{bio}</p>
              <hr />
              <p className="title is-4">Talks :</p>
              {divideInRows(
                talks,
                talk =>
                  talk && (
                    <div className="column is-6" key={talk.id}>
                      <TalkOverview talk={talk} />
                    </div>
                  ),
                2
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  </>
);

export default SpeakerDetails;
