// vue.js/src/components/authentication/Login.vue
<template>
  <form class="container" novalidate>
    <div class="columns is-vcentered">
      <div class="column is-4 is-offset-4">
        <h1 class="title">Sign in</h1>
        <div class="box">
          <label class="label">Email*</label>
          <p class="control">
            <input
              class="input"
              :class="{
                'is-danger':$v.credentials.email.$invalid && $v.credentials.email.$dirty
              }"
              type="email"
              placeholder="jsmith@example.org"
              @blur="$v.credentials.email.$touch()"
              v-model="credentials.email"
              required
            >
          </p>
          <label class="label">Password*</label>
          <p class="control">
            <input
              class="input"
              :class="{
                'is-danger':$v.credentials.password.$invalid && $v.credentials.password.$dirty
              }"
              type="password"
              autocomplete="Password"
              placeholder="●●●●●●●"
              @blur="$v.credentials.password.$touch()"
              v-model="credentials.password"
              required
            >
          </p>
          <p v-if="userNotFound">User not found</p>
          <hr>
          <p class="control">
            <button
              class="button is-outlined is-large is-fullwidth"
              @click.prevent="login()"
              :disabled="$v.$invalid"
            >Login</button>
          </p>
        </div>
        <p class="has-text-centered">
          <router-link to="/authentication/register" active-class="is-active">Register</router-link>
        </p>
      </div>
    </div>
  </form>
</template>
<script>
import {email, maxLength, minLength, required} from 'vuelidate/lib/validators';
import {login} from './authentication.apollo-query';
import auth from './authentication.service';

export default {
  data() {
    return {
      userNotFound: false,
      publicName: '',
      credentials: {
        email: '',
        password: ''
      }
    };
  },
  validations: {
    credentials: {
      email: {
        required,
        email,
        maxLength: maxLength(50)
      },
      password: {
        required,
        maxLength: maxLength(50),
        minLength: minLength(3)
      }
    }
  },
  apollo: {},
  methods: {
    login() {
      // TODO: Write login mutation and execute it
      // Replace Promise.reject() by the correct call
      Promise.reject()
        .then(({data}) => {
          this.userNotFound = false;
          this.publicName = data.signinUser.user.publicName;
          this.storePublicNameInLocalStorage(this.publicName);
          this.navigateToHome();
        })
        .catch(error => {
          console.log(error);
          this.userNotFound = true;
        });
    },
    storePublicNameInLocalStorage(name) {
      auth.savePublicName(name);
    },
    navigateToHome() {
      this.$router.push('/');
    }
  }
};
</script>

// react-app/src/component/authentication/Login.js
import React, { Component } from "react";
import { Mutation } from "react-apollo";
import { Form } from "react-form";
import { Link } from "react-router-dom";
import { errorPropsConfig, validateLoginForm } from "../../utils";
import { LoginForm } from "./LoginForm";

// TODO write a query to signinUser
const LOGIN_MUTATION = undefined;

class Login extends Component {
  onSubmit = mutationFn => values => {
    mutationFn({
      variables: values
    })
      .then(re => {
        this.setState({
          userNotFound: false
        });
        localStorage.setItem("userName", values.email);
        this.props.history.push("/");
      })
      .catch(err => {
        this.setState({
          userNotFound: true
        });
      });
  };

  constructor(props) {
    super(props);

    this.state = {
      userNotFound: false
    };
  }

  render() {
    // TODO Use the LOGIN_MUTATION  query to login

    // Remove this variable when you will get the mutate function from Mutation component
    const mutate = () =>
      alert("You should get the correct function from the mutation component");

    return (
      <div className="section">
        <div className="container">
          <div className="columns is-vcentered">
            <div className="column is-4 is-offset-4">
              <h1 className="title">Sign in</h1>
              <Form
                onSubmit={this.onSubmit(mutate)}
                validate={validateLoginForm}
                className="box"
              >
                {({ submitForm }) => (
                  <LoginForm
                    submitForm={submitForm}
                    errorPropsConfig={errorPropsConfig}
                    userNotFound={this.state.userNotFound}
                  />
                )}
              </Form>
              <p className="has-text-centered">
                <Link to="/authentication/register">Register</Link>
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Login;
